name: Build Android APK

on:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_FORCE_NODE_JS: '20'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    permissions:
      contents: read
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@main
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Web App (Vite)
      run: npm run build

    - name: Initialize Capacitor
      run: if [ ! -f capacitor.config.json ]; then npx cap init "دفتر حساب" "com.studio.invoice" --web-dir=www; fi

    # این مرحله اضافه شده تا ارور Permission denied برطرف شود
    - name: